---
baseurl: /react
url: http://facebook.github.io
permalink: /blog/:year/:month/:day/:title.html
exclude:
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
redcarpet:
  extensions:
  - fenced_code_blocks
pygments: true
name: React
markdown: redcarpet
react_version: 0.6.0-alpha
description: A JavaScript library for building user interfaces
relative_permalinks: true
paginate: 5
paginate_path: /blog/page:num
nav_docs_sections:
- title: Quick Start
  items:
  - id: getting-started
    title: Getting Started
  - id: tutorial
    title: Tutorial
- title: Guides
  items:
  - id: why-react
    title: Why React?
  - id: displaying-data
    title: Displaying Data
    subitems:
    - id: jsx-in-depth
      title: JSX in Depth
    - id: jsx-gotchas
      title: JSX Gotchas
  - id: interactivity-and-dynamic-uis
    title: Interactivity and Dynamic UIs
  - id: multiple-components
    title: Multiple Components
  - id: reusable-components
    title: Reusable Components
  - id: forms
    title: Forms
  - id: working-with-the-browser
    title: Working With the Browser
    subitems:
    - id: more-about-refs
      title: More About Refs
  - id: tooling-integration
    title: Tooling Integration
  - id: addons
    title: Add-ons
  - id: examples
    title: Examples
- title: Cookbook
  items:
  - id: introduction
    title: Introduction
  - id: inline-styles
    title: Inline Styles
- title: Reference
  items:
  - id: top-level-api
    title: Top-Level API
  - id: component-api
    title: Component API
  - id: component-specs
    title: Component Specs and Lifecycle
  - id: tags-and-attributes
    title: Supported Tags and Attributes
  - id: events
    title: Event System
  - id: dom-differences
    title: DOM Differences
