--- 
baseurl: /react
url: http://facebook.github.io
permalink: /blog/:year/:month/:day/:title.html
exclude: 
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
redcarpet: 
  extensions: 
  - fenced_code_blocks
pygments: true
name: React
markdown: redcarpet
react_version: 0.4.0a
description: A JavaScript library for building user interfaces
